### ISSUE TITLE
Private Repo

### ISSUE THREAD

**Issue by mgingras** [mgingras/such-jukebox#1]
Hey, make this repo private please.

**Comment by devinlynch** [comment]
All my privates are used up.  You have any available?  I can transfer ownership to you.

**Comment by mgingras** [comment]
Ahh, nope I’m using like 8 of 5 lol

**Comment by JohnMarsh** [comment]
I have privates free.

**Comment by mgingras** [comment]
ALright, can we transfer this to John?
